version: '3.8'

services:
  nginx:
    image: defectdojo/defectdojo-nginx:latest
    depends_on:
      - uwsgi
    ports:
      - "8080:8080"
    volumes:
      - defectdojo_media:/app/media

  uwsgi:
    image: defectdojo/defectdojo-django:latest
    depends_on:
      - postgres
      - redis
    entrypoint: ['/wait-for-it.sh', 'postgres:5432', '-t', '30', '--', '/entrypoint-uwsgi.sh']
    environment:
      DD_DEBUG: 'False'
      DD_ALLOWED_HOSTS: '*'
      DD_DATABASE_URL: postgresql://defectdojo:defectdojo@postgres:5432/defectdojo
      DD_CELERY_BROKER_URL: redis://redis:6379/0
      DD_SECRET_KEY: 'hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq'
      DD_CREDENTIAL_AES_256_KEY: 'MyZdHZ&TbZ8#vWuS8*NgA*C2@z!4eGCzrW8%&VfBPqM='
    volumes:
      - defectdojo_media:/app/media
    
  celerybeat:
    image: defectdojo/defectdojo-django:latest
    depends_on:
      - postgres
      - redis
    entrypoint: ['/wait-for-it.sh', 'postgres:5432', '-t', '30', '--', '/entrypoint-celery-beat.sh']
    environment:
      DD_DATABASE_URL: postgresql://defectdojo:defectdojo@postgres:5432/defectdojo
      DD_CELERY_BROKER_URL: redis://redis:6379/0
      DD_SECRET_KEY: 'hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq'
      DD_CREDENTIAL_AES_256_KEY: 'MyZdHZ&TbZ8#vWuS8*NgA*C2@z!4eGCzrW8%&VfBPqM='

  celeryworker:
    image: defectdojo/defectdojo-django:latest
    depends_on:
      - postgres
      - redis
    entrypoint: ['/wait-for-it.sh', 'postgres:5432', '-t', '30', '--', '/entrypoint-celery-worker.sh']
    environment:
      DD_DATABASE_URL: postgresql://defectdojo:defectdojo@postgres:5432/defectdojo
      DD_CELERY_BROKER_URL: redis://redis:6379/0
      DD_SECRET_KEY: 'hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq'
      DD_CREDENTIAL_AES_256_KEY: 'MyZdHZ&TbZ8#vWuS8*NgA*C2@z!4eGCzrW8%&VfBPqM='

  initializer:
    image: defectdojo/defectdojo-django:latest
    depends_on:
      - postgres
    entrypoint: ['/wait-for-it.sh', 'postgres:5432', '--', '/entrypoint-initializer.sh']
    environment:
      DD_DATABASE_URL: postgresql://defectdojo:defectdojo@postgres:5432/defectdojo
      DD_ADMIN_USER: admin
      DD_ADMIN_MAIL: admin@defectdojo.local
      DD_ADMIN_FIRST_NAME: Administrator
      DD_ADMIN_LAST_NAME: User
      DD_ADMIN_PASSWORD: defectdojo
      DD_INITIALIZE: true
      DD_SECRET_KEY: 'hhZCp@D28z!n@NED*yB!ROMt+WzsY*iq'
      DD_CREDENTIAL_AES_256_KEY: 'MyZdHZ&TbZ8#vWuS8*NgA*C2@z!4eGCzrW8%&VfBPqM='

  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: defectdojo
      POSTGRES_USER: defectdojo
      POSTGRES_PASSWORD: defectdojo
    volumes:
      - defectdojo_postgres:/var/lib/postgresql/data
    
  redis:
    image: redis:7.0.9-alpine

volumes:
  defectdojo_media: {}
  defectdojo_postgres: {}